apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-parksmap-web
  title: Deploy Parksmap Web Application
  description: Deploy your existing Parksmap application from Quay.io directly to OpenShift
  tags:
    - recommended
    - parksmap
    - openshift
    - deployment
spec:
  owner: platform-team
  type: service
  parameters:
    - title: Application Configuration
      required:
        - name
        - namespace
      properties:
        name:
          title: Application Name
          type: string
          description: Name for your parksmap deployment
          default: 'parksmap-web'
          pattern: '^[a-z0-9-]+$'
        namespace:
          title: Target Namespace
          type: string
          description: OpenShift namespace to deploy to
          default: 'parksmap-demo'
        replicas:
          title: Number of Replicas
          type: integer
          description: Number of pod replicas
          default: 2
          minimum: 1
          maximum: 5
        imageTag:
          title: Image Tag
          type: string
          description: Image tag to deploy
          default: 'latest'
          enum:
            - latest
            - v1.0
            - dev
  steps:
    - id: create-manifests
      name: Generate Deployment Manifests
      action: roadiehq:utils:fs:write
      input:
        path: deployment.yaml
        content: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ${{ parameters.namespace }}
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ${{ parameters.name }}
            namespace: ${{ parameters.namespace }}
            labels:
              app: ${{ parameters.name }}
          spec:
            replicas: ${{ parameters.replicas }}
            selector:
              matchLabels:
                app: ${{ parameters.name }}
            template:
              metadata:
                labels:
                  app: ${{ parameters.name }}
              spec:
                containers:
                - name: parksmap
                  image: quay.io/gpagiata/parksmap-web:${{ parameters.imageTag }}
                  ports:
                  - containerPort: 8080
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "100m"
                    limits:
                      memory: "512Mi"
                      cpu: "500m"
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: ${{ parameters.name }}
            namespace: ${{ parameters.namespace }}
          spec:
            selector:
              app: ${{ parameters.name }}
            ports:
            - port: 8080
              targetPort: 8080
          ---
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: ${{ parameters.name }}
            namespace: ${{ parameters.namespace }}
          spec:
            to:
              kind: Service
              name: ${{ parameters.name }}
            port:
              targetPort: 8080
            tls:
              termination: edge

    - id: apply-deployment
      name: Deploy to OpenShift
      action: kubernetes:apply
      input:
        manifestPath: deployment.yaml
        namespaced: true

  output:
    text:
      - title: Deployment Complete!
        content: |
          🚀 **Parksmap Application Deployed Successfully!**
          
          **Deployment Details:**
          - **Application**: ${{ parameters.name }}
          - **Namespace**: ${{ parameters.namespace }}
          - **Image**: quay.io/gpagiata/parksmap-web:${{ parameters.imageTag }}
          - **Replicas**: ${{ parameters.replicas }}
          
          **Access your application:**
          - Route: https://${{ parameters.name }}-${{ parameters.namespace }}.apps.lme876y3k0d5f0456e.eastus.aroapp.io
          
          **Next Steps:**
          1. Check OpenShift console for pod status
          2. Access the application via the route URL
          3. Monitor application logs if needed
